/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author steve
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prinCard = new javax.swing.JPanel();
        fondoPrincipal = new javax.swing.JPanel();
        labelSalir = new javax.swing.JLabel();
        labelIniciar = new javax.swing.JLabel();
        eleccion = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        labelCosEleccion = new javax.swing.JLabel();
        labelExpx = new javax.swing.JLabel();
        labelArcoTgEleccion = new javax.swing.JLabel();
        labelCosh = new javax.swing.JLabel();
        labelAtgh = new javax.swing.JLabel();
        labelSinEleccion = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        labelArcCosEleccion = new javax.swing.JLabel();
        labelSinh = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelASinEleccion = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        fondoRamanujan1 = new javax.swing.JLabel();
        jlabelSerieRama1 = new javax.swing.JLabel();
        labelLn = new javax.swing.JLabel();
        vistaSin = new javax.swing.JPanel();
        txtSinInput = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        labelLImpiarSin = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        labelIgualSinX = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSinOutput = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        labelBackSin = new javax.swing.JLabel();
        vistaASin = new javax.swing.JPanel();
        txtASinInput = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        btnASinIgual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLimpiarASin = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaASinOutput = new javax.swing.JTextArea();
        jlabelASinAnim = new javax.swing.JLabel();
        btnBackASin = new javax.swing.JLabel();
        vistaCos = new javax.swing.JPanel();
        txtInputCos = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        btnIgualCos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLimpiarCos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaOutputCos = new javax.swing.JTextArea();
        jlabelASinAnim1 = new javax.swing.JLabel();
        btnBackCos = new javax.swing.JLabel();
        vistaArcCos = new javax.swing.JPanel();
        txtInputArcCos = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        btnIgualArcCos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLimpiarArcCos = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaOutputArcCos = new javax.swing.JTextArea();
        labelAnimArcCos = new javax.swing.JLabel();
        btnBackArcCos = new javax.swing.JLabel();
        vistaArcTg = new javax.swing.JPanel();
        txtInputArcTg = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        btnIgualArcTg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLimpiarArcTg = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaOutputArcTg = new javax.swing.JTextArea();
        labelAnimArcCos1 = new javax.swing.JLabel();
        btnBackTg = new javax.swing.JLabel();
        vistaExpx = new javax.swing.JPanel();
        txtInputExpx = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        btnIgualExpx = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnLimpiarExpx = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAreaOutputExpx = new javax.swing.JTextArea();
        labelAnimArcCos2 = new javax.swing.JLabel();
        btnBackExpx = new javax.swing.JLabel();
        vistaLn = new javax.swing.JPanel();
        txtInputLn = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        btnIgualLn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnLimpiarLn = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtAreaOutputLn = new javax.swing.JTextArea();
        labelAnimArcCos3 = new javax.swing.JLabel();
        btnBackLn = new javax.swing.JLabel();
        vistaSinh = new javax.swing.JPanel();
        txtInputSinh = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        btnIgualSinh = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnLimpiarSinh = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtAreaOutputSinh = new javax.swing.JTextArea();
        labelAnimArcCos4 = new javax.swing.JLabel();
        btnBackSinh = new javax.swing.JLabel();
        vistaCosh = new javax.swing.JPanel();
        txtInputCosh = new javax.swing.JTextField();
        jPanel30 = new javax.swing.JPanel();
        btnIgualCosh = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnLimpiarCosh = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtAreaOutputCosh = new javax.swing.JTextArea();
        labelAnimArcCos5 = new javax.swing.JLabel();
        btnBackCosh = new javax.swing.JLabel();
        vistaAtgh = new javax.swing.JPanel();
        txtInputAtgh = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        btnIgualAtgh = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnLimpiarAtgh = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtAreaOutputAtgh = new javax.swing.JTextArea();
        jlabelASinAnim2 = new javax.swing.JLabel();
        btnBackAtgh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(5, 2, 36));
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prinCard.setBackground(new java.awt.Color(5, 2, 36));
        prinCard.setForeground(new java.awt.Color(255, 255, 255));
        prinCard.setMinimumSize(new java.awt.Dimension(900, 600));
        prinCard.setPreferredSize(new java.awt.Dimension(900, 600));
        prinCard.setLayout(new java.awt.CardLayout());

        fondoPrincipal.setBackground(new java.awt.Color(17, 0, 40));
        fondoPrincipal.setForeground(new java.awt.Color(255, 173, 195));
        fondoPrincipal.setMinimumSize(new java.awt.Dimension(900, 600));
        fondoPrincipal.setPreferredSize(new java.awt.Dimension(900, 600));
        fondoPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSalir.setBackground(new java.awt.Color(255, 116, 199));
        labelSalir.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        labelSalir.setForeground(new java.awt.Color(255, 255, 255));
        labelSalir.setText("  Salir ");
        labelSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214)));
        labelSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSalirMouseClicked(evt);
            }
        });
        fondoPrincipal.add(labelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 110, 50));

        labelIniciar.setBackground(new java.awt.Color(255, 116, 199));
        labelIniciar.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        labelIniciar.setForeground(new java.awt.Color(255, 255, 255));
        labelIniciar.setText(" Iniciar");
        labelIniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214)));
        labelIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIniciarMouseClicked(evt);
            }
        });
        fondoPrincipal.add(labelIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 120, 50));

        prinCard.add(fondoPrincipal, "principal");

        eleccion.setBackground(new java.awt.Color(25, 0, 13));
        eleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eleccion.setMinimumSize(new java.awt.Dimension(900, 600));
        eleccion.setPreferredSize(new java.awt.Dimension(900, 600));
        eleccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(25, 0, 13));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCosEleccion.setBackground(new java.awt.Color(255, 116, 199));
        labelCosEleccion.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        labelCosEleccion.setForeground(new java.awt.Color(255, 255, 255));
        labelCosEleccion.setText(" cos(x)");
        labelCosEleccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 204, 51), new java.awt.Color(255, 204, 51)));
        labelCosEleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCosEleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCosEleccionMouseClicked(evt);
            }
        });
        jPanel8.add(labelCosEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 90, 50));

        labelExpx.setBackground(new java.awt.Color(255, 116, 199));
        labelExpx.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        labelExpx.setForeground(new java.awt.Color(255, 255, 255));
        labelExpx.setText(" exp(x)");
        labelExpx.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 204, 51)));
        labelExpx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelExpx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExpxMouseClicked(evt);
            }
        });
        jPanel8.add(labelExpx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 90, 50));

        labelArcoTgEleccion.setBackground(new java.awt.Color(255, 116, 199));
        labelArcoTgEleccion.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        labelArcoTgEleccion.setForeground(new java.awt.Color(255, 255, 255));
        labelArcoTgEleccion.setText(" atg(x)");
        labelArcoTgEleccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 153), new java.awt.Color(255, 51, 153), new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153)));
        labelArcoTgEleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelArcoTgEleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelArcoTgEleccionMouseClicked(evt);
            }
        });
        jPanel8.add(labelArcoTgEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 50));

        labelCosh.setBackground(new java.awt.Color(255, 116, 199));
        labelCosh.setFont(new java.awt.Font("Lucida Bright", 3, 20)); // NOI18N
        labelCosh.setForeground(new java.awt.Color(255, 255, 255));
        labelCosh.setText(" cosh(x)");
        labelCosh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 102), new java.awt.Color(255, 51, 51), new java.awt.Color(204, 255, 51), new java.awt.Color(0, 204, 0)));
        labelCosh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelCosh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelCoshMouseClicked(evt);
            }
        });
        jPanel8.add(labelCosh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 50));

        labelAtgh.setBackground(new java.awt.Color(255, 116, 199));
        labelAtgh.setFont(new java.awt.Font("Lucida Bright", 3, 20)); // NOI18N
        labelAtgh.setForeground(new java.awt.Color(255, 255, 255));
        labelAtgh.setText(" atgh(x)");
        labelAtgh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(153, 0, 204), new java.awt.Color(102, 204, 255), new java.awt.Color(153, 153, 255)));
        labelAtgh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAtgh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAtghMouseClicked(evt);
            }
        });
        jPanel8.add(labelAtgh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 90, 50));

        labelSinEleccion.setBackground(new java.awt.Color(255, 116, 199));
        labelSinEleccion.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        labelSinEleccion.setForeground(new java.awt.Color(255, 255, 255));
        labelSinEleccion.setText(" sin(x)");
        labelSinEleccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(102, 255, 102), new java.awt.Color(102, 255, 102)));
        labelSinEleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSinEleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSinEleccionMouseClicked(evt);
            }
        });
        jPanel8.add(labelSinEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 50));

        eleccion.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 320));

        jPanel10.setBackground(new java.awt.Color(25, 0, 13));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelArcCosEleccion.setBackground(new java.awt.Color(255, 116, 199));
        labelArcCosEleccion.setFont(new java.awt.Font("Lucida Bright", 3, 20)); // NOI18N
        labelArcCosEleccion.setForeground(new java.awt.Color(255, 255, 255));
        labelArcCosEleccion.setText("  acos(x)");
        labelArcCosEleccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51)));
        labelArcCosEleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelArcCosEleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelArcCosEleccionMouseClicked(evt);
            }
        });
        jPanel10.add(labelArcCosEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 100, 50));

        labelSinh.setBackground(new java.awt.Color(255, 116, 199));
        labelSinh.setFont(new java.awt.Font("Lucida Bright", 3, 20)); // NOI18N
        labelSinh.setForeground(new java.awt.Color(255, 255, 255));
        labelSinh.setText("   sinh(x)");
        labelSinh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 102), new java.awt.Color(255, 102, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(102, 51, 255)));
        labelSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSinhMouseClicked(evt);
            }
        });
        jPanel10.add(labelSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 100, 50));

        jLabel5.setBackground(new java.awt.Color(255, 116, 199));
        jLabel5.setFont(new java.awt.Font("Lucida Bright", 3, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  acoh(x)");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 0), new java.awt.Color(255, 255, 204), new java.awt.Color(102, 0, 0), new java.awt.Color(255, 204, 204)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 50));

        jLabel16.setBackground(new java.awt.Color(255, 116, 199));
        jLabel16.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" exp(sinx)");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 50));

        labelASinEleccion.setBackground(new java.awt.Color(255, 116, 199));
        labelASinEleccion.setFont(new java.awt.Font("Lucida Bright", 3, 20)); // NOI18N
        labelASinEleccion.setForeground(new java.awt.Color(255, 255, 255));
        labelASinEleccion.setText("  asin(x)");
        labelASinEleccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 51), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 153, 204), new java.awt.Color(51, 0, 51)));
        labelASinEleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelASinEleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelASinEleccionMouseClicked(evt);
            }
        });
        jPanel10.add(labelASinEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 50));

        jLabel10.setBackground(new java.awt.Color(255, 116, 199));
        jLabel10.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" exp(cosx)");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(153, 204, 255), new java.awt.Color(204, 153, 255)));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 100, 50));

        eleccion.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 270, 310));

        jPanel22.setBackground(new java.awt.Color(25, 0, 13));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 116, 199));
        btnBack.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText(" Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 79, 184), new java.awt.Color(255, 79, 184), new java.awt.Color(255, 79, 184), new java.awt.Color(255, 79, 184)));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel22.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 40));

        eleccion.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 110, 70));

        fondoRamanujan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ramafondo.png"))); // NOI18N
        eleccion.add(fondoRamanujan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 630, 460));

        jlabelSerieRama1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/serierama.png"))); // NOI18N
        eleccion.add(jlabelSerieRama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 540, 140));

        labelLn.setBackground(new java.awt.Color(255, 116, 199));
        labelLn.setFont(new java.awt.Font("Lucida Bright", 3, 20)); // NOI18N
        labelLn.setForeground(new java.awt.Color(255, 255, 255));
        labelLn.setText("  ln(x+1)");
        labelLn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(51, 255, 204), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 0)));
        labelLn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLnMouseClicked(evt);
            }
        });
        eleccion.add(labelLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 100, 50));

        prinCard.add(eleccion, "eleccion");

        vistaSin.setBackground(new java.awt.Color(17, 0, 8));
        vistaSin.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaSin.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaSin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSinInput.setBackground(new java.awt.Color(255, 255, 255));
        txtSinInput.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 14)); // NOI18N
        txtSinInput.setForeground(new java.awt.Color(51, 0, 0));
        txtSinInput.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 91)));
        vistaSin.add(txtSinInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 310, 30));

        jPanel7.setBackground(new java.awt.Color(17, 0, 8));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLImpiarSin.setBackground(new java.awt.Color(255, 116, 199));
        labelLImpiarSin.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        labelLImpiarSin.setForeground(new java.awt.Color(255, 255, 255));
        labelLImpiarSin.setText(" CE");
        labelLImpiarSin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122)));
        labelLImpiarSin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLImpiarSin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLImpiarSinMouseClicked(evt);
            }
        });
        jPanel7.add(labelLImpiarSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 30));

        vistaSin.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 90, 70));

        jPanel21.setBackground(new java.awt.Color(17, 0, 8));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIgualSinX.setBackground(new java.awt.Color(255, 116, 199));
        labelIgualSinX.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        labelIgualSinX.setForeground(new java.awt.Color(255, 255, 255));
        labelIgualSinX.setText("  ~");
        labelIgualSinX.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122)));
        labelIgualSinX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIgualSinX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIgualSinXMouseClicked(evt);
            }
        });
        jPanel21.add(labelIgualSinX, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" ~");
        jPanel21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        vistaSin.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, 70));

        txtAreaSinOutput.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaSinOutput.setColumns(20);
        txtAreaSinOutput.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 3, 24)); // NOI18N
        txtAreaSinOutput.setForeground(new java.awt.Color(51, 0, 0));
        txtAreaSinOutput.setRows(5);
        txtAreaSinOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(249, 0, 119), new java.awt.Color(249, 0, 119)));
        jScrollPane1.setViewportView(txtAreaSinOutput);

        vistaSin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 330, 170));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/animacionsin.gif"))); // NOI18N
        vistaSin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 480, 580));

        labelBackSin.setBackground(new java.awt.Color(255, 116, 199));
        labelBackSin.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        labelBackSin.setForeground(new java.awt.Color(255, 255, 255));
        labelBackSin.setText(" Back");
        labelBackSin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51)));
        labelBackSin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBackSin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackSinMouseClicked(evt);
            }
        });
        vistaSin.add(labelBackSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 40));

        prinCard.add(vistaSin, "vistaSin");

        vistaASin.setBackground(new java.awt.Color(0, 39, 97));
        vistaASin.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaASin.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaASin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtASinInput.setBackground(new java.awt.Color(255, 255, 255));
        txtASinInput.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtASinInput.setForeground(new java.awt.Color(51, 0, 0));
        txtASinInput.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 204)));
        vistaASin.add(txtASinInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, 30));

        jPanel23.setBackground(new java.awt.Color(0, 39, 97));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnASinIgual.setBackground(new java.awt.Color(255, 116, 199));
        btnASinIgual.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnASinIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnASinIgual.setText("  ~");
        btnASinIgual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255)));
        btnASinIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnASinIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnASinIgualMouseClicked(evt);
            }
        });
        jPanel23.add(btnASinIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" ~");
        jPanel23.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        btnLimpiarASin.setBackground(new java.awt.Color(255, 116, 199));
        btnLimpiarASin.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnLimpiarASin.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarASin.setText(" CLC ");
        btnLimpiarASin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        btnLimpiarASin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarASin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarASinMouseClicked(evt);
            }
        });
        jPanel23.add(btnLimpiarASin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 80, 40));

        vistaASin.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 250, 70));

        txtAreaASinOutput.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaASinOutput.setColumns(20);
        txtAreaASinOutput.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 24)); // NOI18N
        txtAreaASinOutput.setForeground(new java.awt.Color(51, 0, 0));
        txtAreaASinOutput.setRows(5);
        txtAreaASinOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));
        jScrollPane2.setViewportView(txtAreaASinOutput);

        vistaASin.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 390, 180));

        jlabelASinAnim.setBackground(new java.awt.Color(255, 255, 255));
        vistaASin.add(jlabelASinAnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 480, 580));

        btnBackASin.setBackground(new java.awt.Color(255, 116, 199));
        btnBackASin.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        btnBackASin.setForeground(new java.awt.Color(255, 255, 255));
        btnBackASin.setText(" Back");
        btnBackASin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(192, 192, 255), new java.awt.Color(192, 192, 255), new java.awt.Color(226, 170, 255), new java.awt.Color(226, 170, 255)));
        btnBackASin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackASin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackASinMouseClicked(evt);
            }
        });
        vistaASin.add(btnBackASin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 40));

        prinCard.add(vistaASin, "vistaASin");

        vistaCos.setBackground(new java.awt.Color(46, 0, 63));
        vistaCos.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaCos.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaCos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInputCos.setBackground(new java.awt.Color(255, 255, 255));
        txtInputCos.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtInputCos.setForeground(new java.awt.Color(51, 0, 0));
        txtInputCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(255, 153, 153), new java.awt.Color(255, 204, 153)));
        vistaCos.add(txtInputCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, 30));

        jPanel24.setBackground(new java.awt.Color(46, 0, 63));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgualCos.setBackground(new java.awt.Color(255, 116, 199));
        btnIgualCos.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnIgualCos.setForeground(new java.awt.Color(255, 255, 255));
        btnIgualCos.setText("  ~");
        btnIgualCos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 174, 17), new java.awt.Color(224, 215, 0)));
        btnIgualCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgualCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualCosMouseClicked(evt);
            }
        });
        jPanel24.add(btnIgualCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" ~");
        jPanel24.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        btnLimpiarCos.setBackground(new java.awt.Color(255, 116, 199));
        btnLimpiarCos.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnLimpiarCos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCos.setText(" CLC");
        btnLimpiarCos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 102), new java.awt.Color(255, 204, 204)));
        btnLimpiarCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarCosMouseClicked(evt);
            }
        });
        jPanel24.add(btnLimpiarCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 80, 40));

        vistaCos.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 240, 70));

        txtAreaOutputCos.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaOutputCos.setColumns(20);
        txtAreaOutputCos.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 24)); // NOI18N
        txtAreaOutputCos.setForeground(new java.awt.Color(51, 0, 0));
        txtAreaOutputCos.setRows(5);
        txtAreaOutputCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 51)));
        jScrollPane3.setViewportView(txtAreaOutputCos);

        vistaCos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 390, 180));

        jlabelASinAnim1.setBackground(new java.awt.Color(255, 255, 255));
        vistaCos.add(jlabelASinAnim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 470, 580));

        btnBackCos.setBackground(new java.awt.Color(255, 116, 199));
        btnBackCos.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        btnBackCos.setForeground(new java.awt.Color(255, 255, 255));
        btnBackCos.setText(" Back");
        btnBackCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 102), new java.awt.Color(255, 102, 153), new java.awt.Color(0, 255, 153), new java.awt.Color(0, 255, 204)));
        btnBackCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackCosMouseClicked(evt);
            }
        });
        vistaCos.add(btnBackCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 40));

        prinCard.add(vistaCos, "vistaCos");

        vistaArcCos.setBackground(new java.awt.Color(115, 19, 19));
        vistaArcCos.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaArcCos.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaArcCos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInputArcCos.setBackground(new java.awt.Color(255, 255, 255));
        txtInputArcCos.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtInputArcCos.setForeground(new java.awt.Color(0, 0, 102));
        txtInputArcCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(223, 128, 252), new java.awt.Color(255, 204, 245), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 204, 153)));
        vistaArcCos.add(txtInputArcCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, 30));

        jPanel25.setBackground(new java.awt.Color(115, 19, 19));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgualArcCos.setBackground(new java.awt.Color(255, 116, 199));
        btnIgualArcCos.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnIgualArcCos.setForeground(new java.awt.Color(255, 255, 255));
        btnIgualArcCos.setText("  ~");
        btnIgualArcCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 153), new java.awt.Color(0, 204, 153), new java.awt.Color(255, 102, 204), new java.awt.Color(255, 153, 204)));
        btnIgualArcCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgualArcCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualArcCosMouseClicked(evt);
            }
        });
        jPanel25.add(btnIgualArcCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" ~");
        jPanel25.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        btnLimpiarArcCos.setBackground(new java.awt.Color(255, 116, 199));
        btnLimpiarArcCos.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnLimpiarArcCos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarArcCos.setText("  CLC ");
        btnLimpiarArcCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnLimpiarArcCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarArcCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarArcCosMouseClicked(evt);
            }
        });
        jPanel25.add(btnLimpiarArcCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 90, 40));

        vistaArcCos.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 260, 70));

        txtAreaOutputArcCos.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaOutputArcCos.setColumns(20);
        txtAreaOutputArcCos.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 24)); // NOI18N
        txtAreaOutputArcCos.setForeground(new java.awt.Color(102, 0, 102));
        txtAreaOutputArcCos.setRows(5);
        txtAreaOutputArcCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(51, 102, 255), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 51)));
        jScrollPane4.setViewportView(txtAreaOutputArcCos);

        vistaArcCos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 390, 180));

        labelAnimArcCos.setBackground(new java.awt.Color(255, 255, 255));
        vistaArcCos.add(labelAnimArcCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 470, 580));

        btnBackArcCos.setBackground(new java.awt.Color(255, 116, 199));
        btnBackArcCos.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        btnBackArcCos.setForeground(new java.awt.Color(255, 255, 255));
        btnBackArcCos.setText(" Back");
        btnBackArcCos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153), new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0)));
        btnBackArcCos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackArcCos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackArcCosMouseClicked(evt);
            }
        });
        vistaArcCos.add(btnBackArcCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 40));

        prinCard.add(vistaArcCos, "vistaArcCos");

        vistaArcTg.setBackground(new java.awt.Color(0, 34, 35));
        vistaArcTg.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaArcTg.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaArcTg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInputArcTg.setBackground(new java.awt.Color(255, 255, 255));
        txtInputArcTg.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtInputArcTg.setForeground(new java.awt.Color(0, 0, 102));
        txtInputArcTg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(223, 128, 252), new java.awt.Color(255, 204, 245), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 204, 153)));
        vistaArcTg.add(txtInputArcTg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, 30));

        jPanel26.setBackground(new java.awt.Color(0, 34, 35));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgualArcTg.setBackground(new java.awt.Color(255, 116, 199));
        btnIgualArcTg.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnIgualArcTg.setForeground(new java.awt.Color(255, 255, 255));
        btnIgualArcTg.setText("  ~");
        btnIgualArcTg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 153), new java.awt.Color(0, 204, 153), new java.awt.Color(255, 102, 204), new java.awt.Color(255, 153, 204)));
        btnIgualArcTg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgualArcTg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualArcTgMouseClicked(evt);
            }
        });
        jPanel26.add(btnIgualArcTg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel8.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" ~");
        jPanel26.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        btnLimpiarArcTg.setBackground(new java.awt.Color(255, 116, 199));
        btnLimpiarArcTg.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnLimpiarArcTg.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarArcTg.setText("  CLC");
        btnLimpiarArcTg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnLimpiarArcTg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarArcTg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarArcTgMouseClicked(evt);
            }
        });
        jPanel26.add(btnLimpiarArcTg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 90, 40));

        vistaArcTg.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 260, 70));

        txtAreaOutputArcTg.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaOutputArcTg.setColumns(20);
        txtAreaOutputArcTg.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 24)); // NOI18N
        txtAreaOutputArcTg.setForeground(new java.awt.Color(102, 0, 102));
        txtAreaOutputArcTg.setRows(5);
        txtAreaOutputArcTg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(51, 102, 255), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 51)));
        jScrollPane5.setViewportView(txtAreaOutputArcTg);

        vistaArcTg.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 390, 180));

        labelAnimArcCos1.setBackground(new java.awt.Color(255, 255, 255));
        vistaArcTg.add(labelAnimArcCos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 470, 580));

        btnBackTg.setBackground(new java.awt.Color(255, 116, 199));
        btnBackTg.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        btnBackTg.setForeground(new java.awt.Color(255, 255, 255));
        btnBackTg.setText(" Back");
        btnBackTg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153), new java.awt.Color(204, 204, 0), new java.awt.Color(204, 204, 0)));
        btnBackTg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackTg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackTgMouseClicked(evt);
            }
        });
        vistaArcTg.add(btnBackTg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 40));

        prinCard.add(vistaArcTg, "vistaArcTg");

        vistaExpx.setBackground(new java.awt.Color(37, 0, 98));
        vistaExpx.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaExpx.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaExpx.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInputExpx.setBackground(new java.awt.Color(255, 255, 255));
        txtInputExpx.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtInputExpx.setForeground(new java.awt.Color(0, 0, 102));
        txtInputExpx.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(223, 128, 252), new java.awt.Color(255, 204, 245), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 204, 153)));
        txtInputExpx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInputExpxMouseClicked(evt);
            }
        });
        vistaExpx.add(txtInputExpx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, 30));

        jPanel27.setBackground(new java.awt.Color(37, 0, 98));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgualExpx.setBackground(new java.awt.Color(255, 116, 199));
        btnIgualExpx.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnIgualExpx.setForeground(new java.awt.Color(102, 255, 204));
        btnIgualExpx.setText("  ~");
        btnIgualExpx.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 153, 255), new java.awt.Color(102, 0, 102)));
        btnIgualExpx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgualExpx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualExpxMouseClicked(evt);
            }
        });
        jPanel27.add(btnIgualExpx, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel9.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 204));
        jLabel9.setText(" ~");
        jPanel27.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        btnLimpiarExpx.setBackground(new java.awt.Color(255, 116, 199));
        btnLimpiarExpx.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnLimpiarExpx.setForeground(new java.awt.Color(153, 255, 204));
        btnLimpiarExpx.setText(" CLC ");
        btnLimpiarExpx.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 153), new java.awt.Color(0, 159, 153), new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153)));
        btnLimpiarExpx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarExpx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarExpxMouseClicked(evt);
            }
        });
        jPanel27.add(btnLimpiarExpx, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 80, 40));

        vistaExpx.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 260, 70));

        txtAreaOutputExpx.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaOutputExpx.setColumns(20);
        txtAreaOutputExpx.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 24)); // NOI18N
        txtAreaOutputExpx.setForeground(new java.awt.Color(102, 0, 102));
        txtAreaOutputExpx.setRows(5);
        txtAreaOutputExpx.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 153, 0), new java.awt.Color(255, 255, 0)));
        jScrollPane6.setViewportView(txtAreaOutputExpx);

        vistaExpx.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 390, 180));

        labelAnimArcCos2.setBackground(new java.awt.Color(255, 255, 255));
        vistaExpx.add(labelAnimArcCos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 470, 580));

        btnBackExpx.setBackground(new java.awt.Color(255, 116, 199));
        btnBackExpx.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        btnBackExpx.setForeground(new java.awt.Color(0, 255, 158));
        btnBackExpx.setText(" Back");
        btnBackExpx.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(204, 204, 0), new java.awt.Color(255, 102, 0)));
        btnBackExpx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackExpx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackExpxMouseClicked(evt);
            }
        });
        vistaExpx.add(btnBackExpx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 40));

        prinCard.add(vistaExpx, "vistaExpx");

        vistaLn.setBackground(new java.awt.Color(102, 102, 0));
        vistaLn.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaLn.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaLn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInputLn.setBackground(new java.awt.Color(255, 255, 255));
        txtInputLn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtInputLn.setForeground(new java.awt.Color(0, 0, 102));
        txtInputLn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(223, 128, 252), new java.awt.Color(255, 204, 245), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 204, 153)));
        txtInputLn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInputLnMouseClicked(evt);
            }
        });
        vistaLn.add(txtInputLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, 30));

        jPanel28.setBackground(new java.awt.Color(102, 102, 0));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgualLn.setBackground(new java.awt.Color(255, 116, 199));
        btnIgualLn.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnIgualLn.setForeground(new java.awt.Color(102, 255, 204));
        btnIgualLn.setText("  ~");
        btnIgualLn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 204), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));
        btnIgualLn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgualLn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualLnMouseClicked(evt);
            }
        });
        jPanel28.add(btnIgualLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel12.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 255, 204));
        jLabel12.setText(" ~");
        jPanel28.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        btnLimpiarLn.setBackground(new java.awt.Color(255, 116, 199));
        btnLimpiarLn.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnLimpiarLn.setForeground(new java.awt.Color(255, 255, 204));
        btnLimpiarLn.setText("  CLC");
        btnLimpiarLn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(51, 255, 255), new java.awt.Color(0, 204, 204)));
        btnLimpiarLn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarLn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarLnMouseClicked(evt);
            }
        });
        jPanel28.add(btnLimpiarLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 90, 40));

        vistaLn.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 260, 70));

        txtAreaOutputLn.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaOutputLn.setColumns(20);
        txtAreaOutputLn.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 24)); // NOI18N
        txtAreaOutputLn.setForeground(new java.awt.Color(102, 0, 102));
        txtAreaOutputLn.setRows(5);
        txtAreaOutputLn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 204), new java.awt.Color(102, 255, 204), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 204)));
        jScrollPane7.setViewportView(txtAreaOutputLn);

        vistaLn.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 390, 180));

        labelAnimArcCos3.setBackground(new java.awt.Color(255, 255, 255));
        vistaLn.add(labelAnimArcCos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 470, 580));

        btnBackLn.setBackground(new java.awt.Color(255, 116, 199));
        btnBackLn.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        btnBackLn.setForeground(new java.awt.Color(255, 204, 204));
        btnBackLn.setText(" Back");
        btnBackLn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 0), new java.awt.Color(0, 255, 0), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 255)));
        btnBackLn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackLn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackLnMouseClicked(evt);
            }
        });
        vistaLn.add(btnBackLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 40));

        prinCard.add(vistaLn, "vistaLn");

        vistaSinh.setBackground(new java.awt.Color(84, 33, 0));
        vistaSinh.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaSinh.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaSinh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInputSinh.setBackground(new java.awt.Color(255, 255, 255));
        txtInputSinh.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtInputSinh.setForeground(new java.awt.Color(0, 0, 102));
        txtInputSinh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(223, 128, 252), new java.awt.Color(255, 204, 245), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 204, 153)));
        txtInputSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtInputSinhMouseClicked(evt);
            }
        });
        vistaSinh.add(txtInputSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, 30));

        jPanel29.setBackground(new java.awt.Color(84, 33, 0));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgualSinh.setBackground(new java.awt.Color(255, 116, 199));
        btnIgualSinh.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnIgualSinh.setForeground(new java.awt.Color(204, 204, 255));
        btnIgualSinh.setText("  ~");
        btnIgualSinh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 153, 255), new java.awt.Color(102, 0, 102)));
        btnIgualSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgualSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualSinhMouseClicked(evt);
            }
        });
        jPanel29.add(btnIgualSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel14.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 255));
        jLabel14.setText(" ~");
        jPanel29.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        btnLimpiarSinh.setBackground(new java.awt.Color(255, 116, 199));
        btnLimpiarSinh.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnLimpiarSinh.setForeground(new java.awt.Color(0, 255, 252));
        btnLimpiarSinh.setText(" CLC ");
        btnLimpiarSinh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 153), new java.awt.Color(0, 159, 153), new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153)));
        btnLimpiarSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarSinhMouseClicked(evt);
            }
        });
        jPanel29.add(btnLimpiarSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 80, 40));

        vistaSinh.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 260, 70));

        txtAreaOutputSinh.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaOutputSinh.setColumns(20);
        txtAreaOutputSinh.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 24)); // NOI18N
        txtAreaOutputSinh.setForeground(new java.awt.Color(102, 0, 102));
        txtAreaOutputSinh.setRows(5);
        txtAreaOutputSinh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 153, 0), new java.awt.Color(255, 255, 0)));
        jScrollPane8.setViewportView(txtAreaOutputSinh);

        vistaSinh.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 390, 180));

        labelAnimArcCos4.setBackground(new java.awt.Color(255, 255, 255));
        vistaSinh.add(labelAnimArcCos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 470, 580));

        btnBackSinh.setBackground(new java.awt.Color(255, 116, 199));
        btnBackSinh.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        btnBackSinh.setForeground(new java.awt.Color(153, 153, 255));
        btnBackSinh.setText(" Back");
        btnBackSinh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(204, 204, 0), new java.awt.Color(255, 102, 0)));
        btnBackSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackSinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackSinhMouseClicked(evt);
            }
        });
        vistaSinh.add(btnBackSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 40));

        prinCard.add(vistaSinh, "vistaSinh");

        vistaCosh.setBackground(new java.awt.Color(244, 0, 123));
        vistaCosh.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaCosh.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaCosh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInputCosh.setBackground(new java.awt.Color(255, 255, 255));
        txtInputCosh.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtInputCosh.setForeground(new java.awt.Color(0, 0, 102));
        txtInputCosh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(43, 0, 17), new java.awt.Color(43, 0, 17), new java.awt.Color(255, 204, 204)));
        vistaCosh.add(txtInputCosh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, 30));

        jPanel30.setBackground(new java.awt.Color(244, 0, 123));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgualCosh.setBackground(new java.awt.Color(255, 116, 199));
        btnIgualCosh.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnIgualCosh.setForeground(new java.awt.Color(204, 255, 255));
        btnIgualCosh.setText("  ~");
        btnIgualCosh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(43, 0, 17), new java.awt.Color(43, 0, 17)));
        btnIgualCosh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgualCosh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualCoshMouseClicked(evt);
            }
        });
        jPanel30.add(btnIgualCosh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel13.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 204));
        jLabel13.setText(" ~");
        jPanel30.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        btnLimpiarCosh.setBackground(new java.awt.Color(255, 116, 199));
        btnLimpiarCosh.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnLimpiarCosh.setForeground(new java.awt.Color(255, 211, 255));
        btnLimpiarCosh.setText("  CLC");
        btnLimpiarCosh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(43, 0, 17), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204), new java.awt.Color(43, 0, 17)));
        btnLimpiarCosh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarCosh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarCoshMouseClicked(evt);
            }
        });
        jPanel30.add(btnLimpiarCosh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 90, 40));

        vistaCosh.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 260, 70));

        txtAreaOutputCosh.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaOutputCosh.setColumns(20);
        txtAreaOutputCosh.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 24)); // NOI18N
        txtAreaOutputCosh.setForeground(new java.awt.Color(102, 0, 102));
        txtAreaOutputCosh.setRows(5);
        txtAreaOutputCosh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(43, 0, 17), new java.awt.Color(43, 0, 17), new java.awt.Color(43, 0, 17), new java.awt.Color(43, 0, 17)));
        jScrollPane9.setViewportView(txtAreaOutputCosh);

        vistaCosh.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 390, 180));

        labelAnimArcCos5.setBackground(new java.awt.Color(255, 255, 255));
        vistaCosh.add(labelAnimArcCos5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 470, 580));

        btnBackCosh.setBackground(new java.awt.Color(255, 116, 199));
        btnBackCosh.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        btnBackCosh.setForeground(new java.awt.Color(255, 186, 243));
        btnBackCosh.setText(" Back");
        btnBackCosh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(43, 0, 17), new java.awt.Color(43, 0, 17), new java.awt.Color(255, 204, 204), new java.awt.Color(255, 204, 204)));
        btnBackCosh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackCosh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackCoshMouseClicked(evt);
            }
        });
        vistaCosh.add(btnBackCosh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 40));

        prinCard.add(vistaCosh, "vistaCosh");

        vistaAtgh.setBackground(new java.awt.Color(1, 0, 19));
        vistaAtgh.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaAtgh.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaAtgh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInputAtgh.setBackground(new java.awt.Color(255, 255, 255));
        txtInputAtgh.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtInputAtgh.setForeground(new java.awt.Color(51, 0, 0));
        txtInputAtgh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(255, 153, 153), new java.awt.Color(255, 204, 153)));
        vistaAtgh.add(txtInputAtgh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, 30));

        jPanel31.setBackground(new java.awt.Color(1, 0, 19));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgualAtgh.setBackground(new java.awt.Color(255, 116, 199));
        btnIgualAtgh.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnIgualAtgh.setForeground(new java.awt.Color(255, 255, 255));
        btnIgualAtgh.setText("  ~");
        btnIgualAtgh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0)));
        btnIgualAtgh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIgualAtgh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIgualAtghMouseClicked(evt);
            }
        });
        jPanel31.add(btnIgualAtgh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel11.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" ~");
        jPanel31.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        btnLimpiarAtgh.setBackground(new java.awt.Color(255, 116, 199));
        btnLimpiarAtgh.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnLimpiarAtgh.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarAtgh.setText(" CLC");
        btnLimpiarAtgh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), new java.awt.Color(0, 51, 255), new java.awt.Color(0, 0, 255)));
        btnLimpiarAtgh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarAtgh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarAtghMouseClicked(evt);
            }
        });
        jPanel31.add(btnLimpiarAtgh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 80, 40));

        vistaAtgh.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 240, 70));

        txtAreaOutputAtgh.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaOutputAtgh.setColumns(20);
        txtAreaOutputAtgh.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 24)); // NOI18N
        txtAreaOutputAtgh.setForeground(new java.awt.Color(51, 0, 0));
        txtAreaOutputAtgh.setRows(5);
        txtAreaOutputAtgh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 51)));
        jScrollPane10.setViewportView(txtAreaOutputAtgh);

        vistaAtgh.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 390, 180));

        jlabelASinAnim2.setBackground(new java.awt.Color(255, 255, 255));
        vistaAtgh.add(jlabelASinAnim2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 470, 580));

        btnBackAtgh.setBackground(new java.awt.Color(255, 116, 199));
        btnBackAtgh.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        btnBackAtgh.setForeground(new java.awt.Color(255, 255, 255));
        btnBackAtgh.setText(" Back");
        btnBackAtgh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(255, 0, 153), new java.awt.Color(255, 255, 255)));
        btnBackAtgh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackAtgh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackAtghMouseClicked(evt);
            }
        });
        vistaAtgh.add(btnBackAtgh, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 70, 40));

        prinCard.add(vistaAtgh, "vistaAtgh");

        getContentPane().add(prinCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIniciarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelIniciarMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseClicked

    private void labelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSalirMouseClicked

    private void labelSinEleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSinEleccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSinEleccionMouseClicked

    private void labelBackSinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackSinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelBackSinMouseClicked

    private void labelIgualSinXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIgualSinXMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelIgualSinXMouseClicked

    private void labelLImpiarSinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLImpiarSinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelLImpiarSinMouseClicked

    private void btnBackASinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackASinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackASinMouseClicked

    private void btnASinIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnASinIgualMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnASinIgualMouseClicked

    private void btnLimpiarASinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarASinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarASinMouseClicked

    private void labelASinEleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelASinEleccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelASinEleccionMouseClicked

    private void btnLimpiarCosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarCosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarCosMouseClicked

    private void btnIgualCosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualCosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualCosMouseClicked

    private void btnBackCosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackCosMouseClicked

    private void labelCosEleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCosEleccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCosEleccionMouseClicked

    private void btnLimpiarArcCosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarArcCosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarArcCosMouseClicked

    private void btnIgualArcCosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualArcCosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualArcCosMouseClicked

    private void btnBackArcCosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackArcCosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackArcCosMouseClicked

    private void labelArcCosEleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelArcCosEleccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelArcCosEleccionMouseClicked

    private void btnIgualArcTgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualArcTgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualArcTgMouseClicked

    private void btnLimpiarArcTgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarArcTgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarArcTgMouseClicked

    private void btnBackTgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackTgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackTgMouseClicked

    private void labelArcoTgEleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelArcoTgEleccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelArcoTgEleccionMouseClicked

    private void btnIgualExpxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualExpxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualExpxMouseClicked

    private void btnLimpiarExpxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarExpxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarExpxMouseClicked

    private void btnBackExpxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackExpxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackExpxMouseClicked

    private void txtInputExpxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInputExpxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputExpxMouseClicked

    private void labelExpxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExpxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelExpxMouseClicked

    private void txtInputLnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInputLnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputLnMouseClicked

    private void btnIgualLnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualLnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualLnMouseClicked

    private void btnLimpiarLnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarLnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarLnMouseClicked

    private void btnBackLnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackLnMouseClicked

    private void labelLnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelLnMouseClicked

    private void txtInputSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInputSinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputSinhMouseClicked

    private void btnIgualSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualSinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualSinhMouseClicked

    private void btnLimpiarSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarSinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarSinhMouseClicked

    private void btnBackSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackSinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackSinhMouseClicked

    private void labelSinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSinhMouseClicked

    private void btnIgualCoshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualCoshMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualCoshMouseClicked

    private void btnLimpiarCoshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarCoshMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarCoshMouseClicked

    private void btnBackCoshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackCoshMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackCoshMouseClicked

    private void labelCoshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelCoshMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelCoshMouseClicked

    private void btnIgualAtghMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIgualAtghMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIgualAtghMouseClicked

    private void btnLimpiarAtghMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarAtghMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarAtghMouseClicked

    private void btnBackAtghMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackAtghMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackAtghMouseClicked

    private void labelAtghMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAtghMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelAtghMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnASinIgual;
    public javax.swing.JLabel btnBack;
    public javax.swing.JLabel btnBackASin;
    public javax.swing.JLabel btnBackArcCos;
    public javax.swing.JLabel btnBackAtgh;
    public javax.swing.JLabel btnBackCos;
    public javax.swing.JLabel btnBackCosh;
    public javax.swing.JLabel btnBackExpx;
    public javax.swing.JLabel btnBackLn;
    public javax.swing.JLabel btnBackSinh;
    public javax.swing.JLabel btnBackTg;
    public javax.swing.JLabel btnIgualArcCos;
    public javax.swing.JLabel btnIgualArcTg;
    public javax.swing.JLabel btnIgualAtgh;
    public javax.swing.JLabel btnIgualCos;
    public javax.swing.JLabel btnIgualCosh;
    public javax.swing.JLabel btnIgualExpx;
    public javax.swing.JLabel btnIgualLn;
    public javax.swing.JLabel btnIgualSinh;
    public javax.swing.JLabel btnLimpiarASin;
    public javax.swing.JLabel btnLimpiarArcCos;
    public javax.swing.JLabel btnLimpiarArcTg;
    public javax.swing.JLabel btnLimpiarAtgh;
    public javax.swing.JLabel btnLimpiarCos;
    public javax.swing.JLabel btnLimpiarCosh;
    public javax.swing.JLabel btnLimpiarExpx;
    public javax.swing.JLabel btnLimpiarLn;
    public javax.swing.JLabel btnLimpiarSinh;
    public javax.swing.JPanel eleccion;
    public javax.swing.JPanel fondoPrincipal;
    private javax.swing.JLabel fondoRamanujan1;
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JLabel jlabelASinAnim;
    public javax.swing.JLabel jlabelASinAnim1;
    public javax.swing.JLabel jlabelASinAnim2;
    private javax.swing.JLabel jlabelSerieRama1;
    public javax.swing.JLabel labelASinEleccion;
    public javax.swing.JLabel labelAnimArcCos;
    public javax.swing.JLabel labelAnimArcCos1;
    public javax.swing.JLabel labelAnimArcCos2;
    public javax.swing.JLabel labelAnimArcCos3;
    public javax.swing.JLabel labelAnimArcCos4;
    public javax.swing.JLabel labelAnimArcCos5;
    public javax.swing.JLabel labelArcCosEleccion;
    public javax.swing.JLabel labelArcoTgEleccion;
    public javax.swing.JLabel labelAtgh;
    public javax.swing.JLabel labelBackSin;
    public javax.swing.JLabel labelCosEleccion;
    public javax.swing.JLabel labelCosh;
    public javax.swing.JLabel labelExpx;
    public javax.swing.JLabel labelIgualSinX;
    public javax.swing.JLabel labelIniciar;
    public javax.swing.JLabel labelLImpiarSin;
    public javax.swing.JLabel labelLn;
    public javax.swing.JLabel labelSalir;
    public javax.swing.JLabel labelSinEleccion;
    public javax.swing.JLabel labelSinh;
    public javax.swing.JPanel prinCard;
    public javax.swing.JTextField txtASinInput;
    public javax.swing.JTextArea txtAreaASinOutput;
    public javax.swing.JTextArea txtAreaOutputArcCos;
    public javax.swing.JTextArea txtAreaOutputArcTg;
    public javax.swing.JTextArea txtAreaOutputAtgh;
    public javax.swing.JTextArea txtAreaOutputCos;
    public javax.swing.JTextArea txtAreaOutputCosh;
    public javax.swing.JTextArea txtAreaOutputExpx;
    public javax.swing.JTextArea txtAreaOutputLn;
    public javax.swing.JTextArea txtAreaOutputSinh;
    public javax.swing.JTextArea txtAreaSinOutput;
    public javax.swing.JTextField txtInputArcCos;
    public javax.swing.JTextField txtInputArcTg;
    public javax.swing.JTextField txtInputAtgh;
    public javax.swing.JTextField txtInputCos;
    public javax.swing.JTextField txtInputCosh;
    public javax.swing.JTextField txtInputExpx;
    public javax.swing.JTextField txtInputLn;
    public javax.swing.JTextField txtInputSinh;
    public javax.swing.JTextField txtSinInput;
    private javax.swing.JPanel vistaASin;
    private javax.swing.JPanel vistaArcCos;
    private javax.swing.JPanel vistaArcTg;
    private javax.swing.JPanel vistaAtgh;
    private javax.swing.JPanel vistaCos;
    private javax.swing.JPanel vistaCosh;
    private javax.swing.JPanel vistaExpx;
    private javax.swing.JPanel vistaLn;
    private javax.swing.JPanel vistaSin;
    private javax.swing.JPanel vistaSinh;
    // End of variables declaration//GEN-END:variables
}
