/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author steve
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prinCard = new javax.swing.JPanel();
        fondoPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelSalir = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelIniciar = new javax.swing.JLabel();
        eleccion = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        labelSinEleccion = new javax.swing.JLabel();
        labelCosEleccion = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        labelASinEleccion = new javax.swing.JLabel();
        labelACosEleccion = new javax.swing.JLabel();
        btnAcos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        fondoRamanujan1 = new javax.swing.JLabel();
        jlabelSerieRama1 = new javax.swing.JLabel();
        vistaSin = new javax.swing.JPanel();
        txtSinInput = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        labelLImpiarSin = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        labelIgualSinX = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaSinOutput = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        labelBackSin = new javax.swing.JLabel();
        vistaASin = new javax.swing.JPanel();
        txtASin = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btnLimpiarASin = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        btnASin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaASin = new javax.swing.JTextArea();
        jlabelASinAnim = new javax.swing.JLabel();
        btnBackASin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(5, 2, 36));
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prinCard.setBackground(new java.awt.Color(5, 2, 36));
        prinCard.setForeground(new java.awt.Color(255, 255, 255));
        prinCard.setMinimumSize(new java.awt.Dimension(900, 600));
        prinCard.setPreferredSize(new java.awt.Dimension(900, 600));
        prinCard.setLayout(new java.awt.CardLayout());

        fondoPrincipal.setBackground(new java.awt.Color(17, 0, 40));
        fondoPrincipal.setForeground(new java.awt.Color(255, 173, 195));
        fondoPrincipal.setMinimumSize(new java.awt.Dimension(900, 600));
        fondoPrincipal.setPreferredSize(new java.awt.Dimension(900, 600));
        fondoPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(17, 0, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSalir.setBackground(new java.awt.Color(255, 116, 199));
        labelSalir.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        labelSalir.setForeground(new java.awt.Color(255, 255, 255));
        labelSalir.setText("  Salir");
        labelSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214)));
        labelSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSalirMouseClicked(evt);
            }
        });
        jPanel2.add(labelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        fondoPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 130, 70));

        jPanel3.setBackground(new java.awt.Color(17, 0, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIniciar.setBackground(new java.awt.Color(255, 116, 199));
        labelIniciar.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        labelIniciar.setForeground(new java.awt.Color(255, 255, 255));
        labelIniciar.setText(" Iniciar");
        labelIniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214), new java.awt.Color(255, 155, 214)));
        labelIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIniciarMouseClicked(evt);
            }
        });
        jPanel3.add(labelIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 30));

        fondoPrincipal.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 140, 70));

        prinCard.add(fondoPrincipal, "principal");

        eleccion.setBackground(new java.awt.Color(25, 0, 13));
        eleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eleccion.setMinimumSize(new java.awt.Dimension(900, 600));
        eleccion.setPreferredSize(new java.awt.Dimension(900, 600));
        eleccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(25, 0, 13));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSinEleccion.setBackground(new java.awt.Color(255, 116, 199));
        labelSinEleccion.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        labelSinEleccion.setForeground(new java.awt.Color(255, 255, 255));
        labelSinEleccion.setText(" sin(x)");
        labelSinEleccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(102, 255, 102), new java.awt.Color(102, 255, 102)));
        labelSinEleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSinEleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSinEleccionMouseClicked(evt);
            }
        });
        jPanel8.add(labelSinEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 30));

        labelCosEleccion.setBackground(new java.awt.Color(255, 116, 199));
        labelCosEleccion.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        labelCosEleccion.setForeground(new java.awt.Color(255, 255, 255));
        labelCosEleccion.setText(" cos(x)");
        labelCosEleccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 204, 51), new java.awt.Color(255, 204, 51)));
        labelCosEleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(labelCosEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 80, 30));

        jLabel14.setBackground(new java.awt.Color(255, 116, 199));
        jLabel14.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" acos(x)");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 255, 51), new java.awt.Color(255, 204, 51)));
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 80, 30));

        jLabel15.setBackground(new java.awt.Color(255, 116, 199));
        jLabel15.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" acos(x)");
        jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 153), new java.awt.Color(255, 51, 153), new java.awt.Color(255, 153, 153), new java.awt.Color(255, 153, 153)));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 30));

        jLabel11.setBackground(new java.awt.Color(255, 116, 199));
        jLabel11.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" acos(x)");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 102), new java.awt.Color(255, 51, 51), new java.awt.Color(204, 255, 51), new java.awt.Color(0, 204, 0)));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 80, 30));

        jLabel17.setBackground(new java.awt.Color(255, 116, 199));
        jLabel17.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" acos(x)");
        jLabel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 51, 102), new java.awt.Color(153, 0, 204), new java.awt.Color(102, 204, 255), new java.awt.Color(153, 153, 255)));
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 80, 30));

        eleccion.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 320));

        jPanel10.setBackground(new java.awt.Color(25, 0, 13));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelASinEleccion.setBackground(new java.awt.Color(255, 116, 199));
        labelASinEleccion.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        labelASinEleccion.setForeground(new java.awt.Color(255, 255, 255));
        labelASinEleccion.setText(" asin(x)");
        labelASinEleccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 51), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 153, 204), new java.awt.Color(51, 0, 51)));
        labelASinEleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelASinEleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelASinEleccionMouseClicked(evt);
            }
        });
        jPanel10.add(labelASinEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        labelACosEleccion.setBackground(new java.awt.Color(255, 116, 199));
        labelACosEleccion.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        labelACosEleccion.setForeground(new java.awt.Color(255, 255, 255));
        labelACosEleccion.setText(" acos(x)");
        labelACosEleccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51)));
        labelACosEleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(labelACosEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 80, 30));

        btnAcos.setBackground(new java.awt.Color(255, 116, 199));
        btnAcos.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        btnAcos.setForeground(new java.awt.Color(255, 255, 255));
        btnAcos.setText(" acos(x)");
        btnAcos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(51, 255, 204), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 0)));
        btnAcos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(btnAcos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 30));

        jLabel13.setBackground(new java.awt.Color(255, 116, 199));
        jLabel13.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" acos(x)");
        jLabel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 102), new java.awt.Color(255, 102, 255), new java.awt.Color(204, 153, 255), new java.awt.Color(102, 51, 255)));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 80, 30));

        jLabel16.setBackground(new java.awt.Color(255, 116, 199));
        jLabel16.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" acos(x)");
        jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 204), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 80, 30));

        jLabel5.setBackground(new java.awt.Color(255, 116, 199));
        jLabel5.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" acos(x)");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 0), new java.awt.Color(255, 255, 204), new java.awt.Color(102, 0, 0), new java.awt.Color(255, 204, 204)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, 30));

        eleccion.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 230, 310));

        jPanel12.setBackground(new java.awt.Color(25, 0, 13));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 116, 199));
        jLabel10.setFont(new java.awt.Font("Lucida Bright", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" acos(x)");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 204, 204), new java.awt.Color(204, 204, 255), new java.awt.Color(153, 204, 255), new java.awt.Color(204, 153, 255)));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        eleccion.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 100, 60));

        jPanel22.setBackground(new java.awt.Color(25, 0, 13));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(255, 116, 199));
        btnBack.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText(" Back");
        btnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 79, 184), new java.awt.Color(255, 79, 184), new java.awt.Color(255, 79, 184), new java.awt.Color(255, 79, 184)));
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel22.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        eleccion.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 110, 70));

        fondoRamanujan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ramafondo.png"))); // NOI18N
        eleccion.add(fondoRamanujan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 630, 460));

        jlabelSerieRama1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/serierama.png"))); // NOI18N
        eleccion.add(jlabelSerieRama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 540, 140));

        prinCard.add(eleccion, "eleccion");

        vistaSin.setBackground(new java.awt.Color(17, 0, 8));
        vistaSin.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaSin.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaSin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSinInput.setBackground(new java.awt.Color(255, 255, 255));
        txtSinInput.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 14)); // NOI18N
        txtSinInput.setForeground(new java.awt.Color(51, 0, 0));
        txtSinInput.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 91)));
        vistaSin.add(txtSinInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 310, 30));

        jPanel7.setBackground(new java.awt.Color(17, 0, 8));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLImpiarSin.setBackground(new java.awt.Color(255, 116, 199));
        labelLImpiarSin.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        labelLImpiarSin.setForeground(new java.awt.Color(255, 255, 255));
        labelLImpiarSin.setText(" CE");
        labelLImpiarSin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122)));
        labelLImpiarSin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLImpiarSin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLImpiarSinMouseClicked(evt);
            }
        });
        jPanel7.add(labelLImpiarSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 30));

        vistaSin.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 90, 70));

        jPanel21.setBackground(new java.awt.Color(17, 0, 8));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIgualSinX.setBackground(new java.awt.Color(255, 116, 199));
        labelIgualSinX.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        labelIgualSinX.setForeground(new java.awt.Color(255, 255, 255));
        labelIgualSinX.setText("  ~");
        labelIgualSinX.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122), new java.awt.Color(255, 0, 122)));
        labelIgualSinX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIgualSinX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIgualSinXMouseClicked(evt);
            }
        });
        jPanel21.add(labelIgualSinX, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" ~");
        jPanel21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        vistaSin.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, 70));

        txtAreaSinOutput.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaSinOutput.setColumns(20);
        txtAreaSinOutput.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 3, 24)); // NOI18N
        txtAreaSinOutput.setForeground(new java.awt.Color(51, 0, 0));
        txtAreaSinOutput.setRows(5);
        txtAreaSinOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(249, 0, 119), new java.awt.Color(249, 0, 119)));
        jScrollPane1.setViewportView(txtAreaSinOutput);

        vistaSin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 330, 170));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/animacionsin.gif"))); // NOI18N
        vistaSin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 480, 580));

        labelBackSin.setBackground(new java.awt.Color(255, 116, 199));
        labelBackSin.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        labelBackSin.setForeground(new java.awt.Color(255, 255, 255));
        labelBackSin.setText(" Back");
        labelBackSin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51)));
        labelBackSin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBackSin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackSinMouseClicked(evt);
            }
        });
        vistaSin.add(labelBackSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 30));

        prinCard.add(vistaSin, "vistaSin");

        vistaASin.setBackground(new java.awt.Color(0, 39, 97));
        vistaASin.setMinimumSize(new java.awt.Dimension(900, 600));
        vistaASin.setPreferredSize(new java.awt.Dimension(900, 600));
        vistaASin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtASin.setBackground(new java.awt.Color(255, 255, 255));
        txtASin.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtASin.setForeground(new java.awt.Color(51, 0, 0));
        txtASin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 204)));
        vistaASin.add(txtASin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 270, 30));

        jPanel9.setBackground(new java.awt.Color(0, 39, 97));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiarASin.setBackground(new java.awt.Color(255, 116, 199));
        btnLimpiarASin.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnLimpiarASin.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarASin.setText(" CE");
        btnLimpiarASin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        btnLimpiarASin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiarASin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarASinMouseClicked(evt);
            }
        });
        jPanel9.add(btnLimpiarASin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 30));

        vistaASin.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 90, 70));

        jPanel23.setBackground(new java.awt.Color(0, 39, 97));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnASin.setBackground(new java.awt.Color(255, 116, 199));
        btnASin.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        btnASin.setForeground(new java.awt.Color(255, 255, 255));
        btnASin.setText("  ~");
        btnASin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255)));
        btnASin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnASin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnASinMouseClicked(evt);
            }
        });
        jPanel23.add(btnASin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jLabel4.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" ~");
        jPanel23.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 30, -1));

        vistaASin.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, 70));

        txtAreaASin.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaASin.setColumns(20);
        txtAreaASin.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 24)); // NOI18N
        txtAreaASin.setForeground(new java.awt.Color(51, 0, 0));
        txtAreaASin.setRows(5);
        txtAreaASin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));
        jScrollPane2.setViewportView(txtAreaASin);

        vistaASin.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 390, 180));

        jlabelASinAnim.setBackground(new java.awt.Color(255, 255, 255));
        vistaASin.add(jlabelASinAnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 480, 580));

        btnBackASin.setBackground(new java.awt.Color(255, 116, 199));
        btnBackASin.setFont(new java.awt.Font("Book Antiqua", 3, 24)); // NOI18N
        btnBackASin.setForeground(new java.awt.Color(255, 255, 255));
        btnBackASin.setText(" Back");
        btnBackASin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(192, 192, 255), new java.awt.Color(192, 192, 255), new java.awt.Color(226, 170, 255), new java.awt.Color(226, 170, 255)));
        btnBackASin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackASin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackASinMouseClicked(evt);
            }
        });
        vistaASin.add(btnBackASin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 70, 30));

        prinCard.add(vistaASin, "vistaASin");

        getContentPane().add(prinCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIniciarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelIniciarMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseClicked

    private void labelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSalirMouseClicked

    private void labelSinEleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSinEleccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSinEleccionMouseClicked

    private void labelBackSinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackSinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelBackSinMouseClicked

    private void labelIgualSinXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIgualSinXMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelIgualSinXMouseClicked

    private void labelLImpiarSinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLImpiarSinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelLImpiarSinMouseClicked

    private void btnBackASinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackASinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackASinMouseClicked

    private void btnASinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnASinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnASinMouseClicked

    private void btnLimpiarASinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarASinMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarASinMouseClicked

    private void labelASinEleccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelASinEleccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelASinEleccionMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnASin;
    public javax.swing.JLabel btnAcos;
    public javax.swing.JLabel btnBack;
    public javax.swing.JLabel btnBackASin;
    public javax.swing.JLabel btnLimpiarASin;
    public javax.swing.JPanel eleccion;
    public javax.swing.JPanel fondoPrincipal;
    private javax.swing.JLabel fondoRamanujan1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel jlabelASinAnim;
    private javax.swing.JLabel jlabelSerieRama1;
    public javax.swing.JLabel labelACosEleccion;
    public javax.swing.JLabel labelASinEleccion;
    public javax.swing.JLabel labelBackSin;
    public javax.swing.JLabel labelCosEleccion;
    public javax.swing.JLabel labelIgualSinX;
    public javax.swing.JLabel labelIniciar;
    public javax.swing.JLabel labelLImpiarSin;
    public javax.swing.JLabel labelSalir;
    public javax.swing.JLabel labelSinEleccion;
    public javax.swing.JPanel prinCard;
    public javax.swing.JTextField txtASin;
    public javax.swing.JTextArea txtAreaASin;
    public javax.swing.JTextArea txtAreaSinOutput;
    public javax.swing.JTextField txtSinInput;
    private javax.swing.JPanel vistaASin;
    private javax.swing.JPanel vistaSin;
    // End of variables declaration//GEN-END:variables
}
