/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package modelo;

/**
 *
 * @author steve
 */
public class ValorTabla {
    
    public static double obtenerValor(String caso) {
        if (caso.equalsIgnoreCase("pi")) return ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("pi*2")) return ConstantesMatematicas.pi * 2;
        if (caso.equalsIgnoreCase("pi*3")) return ConstantesMatematicas.pi * 3;
        if (caso.equalsIgnoreCase("pi*4")) return ConstantesMatematicas.pi * 4;
        if (caso.equalsIgnoreCase("pi*5")) return ConstantesMatematicas.pi * 5;
        if (caso.equalsIgnoreCase("pi*6")) return ConstantesMatematicas.pi * 6;
        if (caso.equalsIgnoreCase("pi*7")) return ConstantesMatematicas.pi * 7;
        if (caso.equalsIgnoreCase("pi*8")) return ConstantesMatematicas.pi * 8;
        if (caso.equalsIgnoreCase("pi*9")) return ConstantesMatematicas.pi * 9;
        if (caso.equalsIgnoreCase("pi*10")) return ConstantesMatematicas.pi * 10;
        if (caso.equalsIgnoreCase("pi*100")) return ConstantesMatematicas.pi * 100;
        if (caso.equalsIgnoreCase("pi/2")) return ConstantesMatematicas.pi / 2;
        if (caso.equalsIgnoreCase("pi/3")) return ConstantesMatematicas.pi / 3;
        if (caso.equalsIgnoreCase("pi/4")) return ConstantesMatematicas.pi / 4;
        if (caso.equalsIgnoreCase("pi/5")) return ConstantesMatematicas.pi / 5;
        if (caso.equalsIgnoreCase("pi/6")) return ConstantesMatematicas.pi / 6;
        if (caso.equalsIgnoreCase("pi/7")) return ConstantesMatematicas.pi / 7;
        if (caso.equalsIgnoreCase("pi/8")) return ConstantesMatematicas.pi / 8;
        if (caso.equalsIgnoreCase("pi/9")) return ConstantesMatematicas.pi / 9;
        if (caso.equalsIgnoreCase("pi/10")) return ConstantesMatematicas.pi / 10;
        if (caso.equalsIgnoreCase("pi/100")) return ConstantesMatematicas.pi / 100;
        if (caso.equalsIgnoreCase("1/pi")) return 1 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("2/pi")) return 2 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("3/pi")) return 3 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("4/pi")) return 4 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("5/pi")) return 5 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("6/pi")) return 6 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("7/pi")) return 7 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("8/pi")) return 8 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("9/pi")) return 9 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("10/pi")) return 10 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("100/pi")) return 100 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("pi*3/2")) return ConstantesMatematicas.pi * 3 / 2;
        if (caso.equalsIgnoreCase("pi*2/3")) return ConstantesMatematicas.pi * 2 / 3;
        if (caso.equalsIgnoreCase("pi*3/4")) return ConstantesMatematicas.pi * 3 / 4;
        if (caso.equalsIgnoreCase("pi*5/6")) return ConstantesMatematicas.pi * 5 / 6;
        if (caso.equalsIgnoreCase("pi*4/3")) return ConstantesMatematicas.pi * 4 / 3;
        if (caso.equalsIgnoreCase("pi*6/5")) return ConstantesMatematicas.pi * 6 / 5;
        if (caso.equalsIgnoreCase("pi*7/2")) return ConstantesMatematicas.pi * 7 / 2;
        if (caso.equalsIgnoreCase("pi*9/2")) return ConstantesMatematicas.pi * 9 / 2;
        if (caso.equalsIgnoreCase("pi*2/9")) return ConstantesMatematicas.pi * 2 / 9;
        if (caso.equalsIgnoreCase("pi*7/8")) return ConstantesMatematicas.pi * 7 / 8;
        if (caso.equalsIgnoreCase("pi*8/7")) return ConstantesMatematicas.pi * 8 / 7;
        if (caso.equalsIgnoreCase("pi*2/7")) return ConstantesMatematicas.pi * 2 / 7;
        if (caso.equalsIgnoreCase("2*pi")) return 2 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("3*pi")) return 3 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("4*pi")) return 4 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("5*pi")) return 5 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("6*pi")) return 6 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("7*pi")) return 7 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("8*pi")) return 8 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("9*pi")) return 9 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("10*pi")) return 10 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("100*pi")) return 100 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("3*pi/2")) return 3 * ConstantesMatematicas.pi / 2;
        if (caso.equalsIgnoreCase("2*pi/3")) return 2 * ConstantesMatematicas.pi / 3;
        if (caso.equalsIgnoreCase("3*pi/4")) return 3 * ConstantesMatematicas.pi / 4;
        if (caso.equalsIgnoreCase("5*pi/6")) return 5 * ConstantesMatematicas.pi / 6;
        if (caso.equalsIgnoreCase("4*pi/3")) return 4 * ConstantesMatematicas.pi / 3;
        if (caso.equalsIgnoreCase("6*pi/5")) return 6 * ConstantesMatematicas.pi / 5;
        if (caso.equalsIgnoreCase("7*pi/2")) return 7 * ConstantesMatematicas.pi / 2;
        if (caso.equalsIgnoreCase("9*pi/2")) return 9 * ConstantesMatematicas.pi / 2;
        if (caso.equalsIgnoreCase("2*pi/9")) return 2 * ConstantesMatematicas.pi / 9;
        if (caso.equalsIgnoreCase("7*pi/8")) return 7 * ConstantesMatematicas.pi / 8;
        if (caso.equalsIgnoreCase("8*pi/7")) return 8 * ConstantesMatematicas.pi / 7;
        if (caso.equalsIgnoreCase("2*pi/7")) return 2 * ConstantesMatematicas.pi / 7;
        if (caso.equalsIgnoreCase("e")) return ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("e*2")) return ConstantesMatematicas.e * 2;
        if (caso.equalsIgnoreCase("e*3")) return ConstantesMatematicas.e * 3;
        if (caso.equalsIgnoreCase("e*4")) return ConstantesMatematicas.e * 4;
        if (caso.equalsIgnoreCase("e*5")) return ConstantesMatematicas.e * 5;
        if (caso.equalsIgnoreCase("e*6")) return ConstantesMatematicas.e * 6;
        if (caso.equalsIgnoreCase("e*7")) return ConstantesMatematicas.e * 7;
        if (caso.equalsIgnoreCase("e*8")) return ConstantesMatematicas.e * 8;
        if (caso.equalsIgnoreCase("e*9")) return ConstantesMatematicas.e * 9;
        if (caso.equalsIgnoreCase("e*10")) return ConstantesMatematicas.e * 10;
        if (caso.equalsIgnoreCase("e*100")) return ConstantesMatematicas.e * 100;
        if (caso.equalsIgnoreCase("e/2")) return ConstantesMatematicas.e / 2;
        if (caso.equalsIgnoreCase("e/3")) return ConstantesMatematicas.e / 3;
        if (caso.equalsIgnoreCase("e/4")) return ConstantesMatematicas.e / 4;
        if (caso.equalsIgnoreCase("e/5")) return ConstantesMatematicas.e / 5;
        if (caso.equalsIgnoreCase("e/6")) return ConstantesMatematicas.e / 6;
        if (caso.equalsIgnoreCase("e/7")) return ConstantesMatematicas.e / 7;
        if (caso.equalsIgnoreCase("e/8")) return ConstantesMatematicas.e / 8;
        if (caso.equalsIgnoreCase("e/9")) return ConstantesMatematicas.e / 9;
        if (caso.equalsIgnoreCase("e/10")) return ConstantesMatematicas.e / 10;
        if (caso.equalsIgnoreCase("e/100")) return ConstantesMatematicas.e / 100;
        if (caso.equalsIgnoreCase("1/e")) return 1 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("2/e")) return 2 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("3/e")) return 3 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("4/e")) return 4 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("5/e")) return 5 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("6/e")) return 6 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("7/e")) return 7 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("8/e")) return 8 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("9/e")) return 9 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("10/e")) return 10 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("100/e")) return 100 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("e*3/2")) return ConstantesMatematicas.e * 3 / 2;
        if (caso.equalsIgnoreCase("e*2/3")) return ConstantesMatematicas.e * 2 / 3;
        if (caso.equalsIgnoreCase("e*3/4")) return ConstantesMatematicas.e * 3 / 4;
        if (caso.equalsIgnoreCase("e*5/6")) return ConstantesMatematicas.e * 5 / 6;
        if (caso.equalsIgnoreCase("e*4/3")) return ConstantesMatematicas.e * 4 / 3;
        if (caso.equalsIgnoreCase("e*6/5")) return ConstantesMatematicas.e * 6 / 5;
        if (caso.equalsIgnoreCase("e*7/2")) return ConstantesMatematicas.e * 7 / 2;
        if (caso.equalsIgnoreCase("e*9/2")) return ConstantesMatematicas.e * 9 / 2;
        if (caso.equalsIgnoreCase("e*2/9")) return ConstantesMatematicas.e * 2 / 9;
        if (caso.equalsIgnoreCase("e*7/8")) return ConstantesMatematicas.e * 7 / 8;
        if (caso.equalsIgnoreCase("e*8/7")) return ConstantesMatematicas.e * 8 / 7;
        if (caso.equalsIgnoreCase("e*2/7")) return ConstantesMatematicas.e * 2 / 7;
        if (caso.equalsIgnoreCase("2*e")) return 2 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("3*e")) return 3 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("4*e")) return 4 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("5*e")) return 5 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("6*e")) return 6 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("7*e")) return 7 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("8*e")) return 8 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("9*e")) return 9 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("10*e")) return 10 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("100*e")) return 100 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("3*e/2")) return 3 * ConstantesMatematicas.e / 2;
        if (caso.equalsIgnoreCase("2*e/3")) return 2 * ConstantesMatematicas.e / 3;
        if (caso.equalsIgnoreCase("3*e/4")) return 3 * ConstantesMatematicas.e / 4;
        if (caso.equalsIgnoreCase("5*e/6")) return 5 * ConstantesMatematicas.e / 6;
        if (caso.equalsIgnoreCase("4*e/3")) return 4 * ConstantesMatematicas.e / 3;
        if (caso.equalsIgnoreCase("6*e/5")) return 6 * ConstantesMatematicas.e / 5;
        if (caso.equalsIgnoreCase("7*e/2")) return 7 * ConstantesMatematicas.e / 2;
        if (caso.equalsIgnoreCase("9*e/2")) return 9 * ConstantesMatematicas.e / 2;
        if (caso.equalsIgnoreCase("2*e/9")) return 2 * ConstantesMatematicas.e / 9;
        if (caso.equalsIgnoreCase("7*e/8")) return 7 * ConstantesMatematicas.e / 8;
        if (caso.equalsIgnoreCase("8*e/7")) return 8 * ConstantesMatematicas.e / 7;
        if (caso.equalsIgnoreCase("2*e/7")) return 2 * ConstantesMatematicas.e / 7;
         if (caso.equalsIgnoreCase("-pi")) return -ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-pi*2")) return -ConstantesMatematicas.pi * 2;
        if (caso.equalsIgnoreCase("-pi*3")) return -ConstantesMatematicas.pi * 3;
        if (caso.equalsIgnoreCase("-pi*4")) return -ConstantesMatematicas.pi * 4;
        if (caso.equalsIgnoreCase("-pi*5")) return -ConstantesMatematicas.pi * 5;
        if (caso.equalsIgnoreCase("-pi*6")) return -ConstantesMatematicas.pi * 6;
        if (caso.equalsIgnoreCase("-pi*7")) return -ConstantesMatematicas.pi * 7;
        if (caso.equalsIgnoreCase("-pi*8")) return -ConstantesMatematicas.pi * 8;
        if (caso.equalsIgnoreCase("-pi*9")) return -ConstantesMatematicas.pi * 9;
        if (caso.equalsIgnoreCase("-pi*10")) return -ConstantesMatematicas.pi * 10;
        if (caso.equalsIgnoreCase("-pi*100")) return -ConstantesMatematicas.pi * 100;
        if (caso.equalsIgnoreCase("-pi/2")) return -ConstantesMatematicas.pi / 2;
        if (caso.equalsIgnoreCase("-pi/3")) return -ConstantesMatematicas.pi / 3;
        if (caso.equalsIgnoreCase("-pi/4")) return -ConstantesMatematicas.pi / 4;
        if (caso.equalsIgnoreCase("-pi/5")) return -ConstantesMatematicas.pi / 5;
        if (caso.equalsIgnoreCase("-pi/6")) return -ConstantesMatematicas.pi / 6;
        if (caso.equalsIgnoreCase("-pi/7")) return -ConstantesMatematicas.pi / 7;
        if (caso.equalsIgnoreCase("-pi/8")) return -ConstantesMatematicas.pi / 8;
        if (caso.equalsIgnoreCase("-pi/9")) return -ConstantesMatematicas.pi / 9;
        if (caso.equalsIgnoreCase("-pi/10")) return -ConstantesMatematicas.pi / 10;
        if (caso.equalsIgnoreCase("-pi/100")) return -ConstantesMatematicas.pi / 100;
        if (caso.equalsIgnoreCase("-1/pi")) return -1 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-2/pi")) return -2 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-3/pi")) return -3 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-4/pi")) return -4 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-5/pi")) return -5 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-6/pi")) return -6 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-7/pi")) return -7 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-8/pi")) return -8 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-9/pi")) return -9 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-10/pi")) return -10 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-100/pi")) return -100 / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-pi*3/2")) return -ConstantesMatematicas.pi * 3 / 2;
        if (caso.equalsIgnoreCase("-pi*2/3")) return -ConstantesMatematicas.pi * 2 / 3;
        if (caso.equalsIgnoreCase("-pi*3/4")) return -ConstantesMatematicas.pi * 3 / 4;
        if (caso.equalsIgnoreCase("-pi*5/6")) return -ConstantesMatematicas.pi * 5 / 6;
        if (caso.equalsIgnoreCase("-pi*4/3")) return -ConstantesMatematicas.pi * 4 / 3;
        if (caso.equalsIgnoreCase("-pi*6/5")) return -ConstantesMatematicas.pi * 6 / 5;
        if (caso.equalsIgnoreCase("-pi*7/2")) return -ConstantesMatematicas.pi * 7 / 2;
        if (caso.equalsIgnoreCase("-pi*9/2")) return -ConstantesMatematicas.pi * 9 / 2;
        if (caso.equalsIgnoreCase("-pi*2/9")) return -ConstantesMatematicas.pi * 2 / 9;
        if (caso.equalsIgnoreCase("-pi*7/8")) return -ConstantesMatematicas.pi * 7 / 8;
        if (caso.equalsIgnoreCase("-pi*8/7")) return -ConstantesMatematicas.pi * 8 / 7;
        if (caso.equalsIgnoreCase("-pi*2/7")) return -ConstantesMatematicas.pi * 2 / 7;
        if (caso.equalsIgnoreCase("-2*pi")) return -2 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-3*pi")) return -3 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-4*pi")) return -4 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-5*pi")) return -5 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-6*pi")) return -6 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-7*pi")) return -7 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-8*pi")) return -8 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-9*pi")) return -9 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-10*pi")) return -10 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-100*pi")) return -100 * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-3*pi/2")) return -3 * ConstantesMatematicas.pi / 2;
        if (caso.equalsIgnoreCase("-2*pi/3")) return -2 * ConstantesMatematicas.pi / 3;
        if (caso.equalsIgnoreCase("-3*pi/4")) return -3 * ConstantesMatematicas.pi / 4;
        if (caso.equalsIgnoreCase("-5*pi/6")) return -5 * ConstantesMatematicas.pi / 6;
        if (caso.equalsIgnoreCase("-4*pi/3")) return -4 * ConstantesMatematicas.pi / 3;
        if (caso.equalsIgnoreCase("-6*pi/5")) return -6 * ConstantesMatematicas.pi / 5;
        if (caso.equalsIgnoreCase("-7*pi/2")) return -7 * ConstantesMatematicas.pi / 2;
        if (caso.equalsIgnoreCase("-9*pi/2")) return -9 * ConstantesMatematicas.pi / 2;
        if (caso.equalsIgnoreCase("-2*pi/9")) return -2 * ConstantesMatematicas.pi / 9;
        if (caso.equalsIgnoreCase("-7*pi/8")) return -7 * ConstantesMatematicas.pi / 8;
        if (caso.equalsIgnoreCase("-8*pi/7")) return -8 * ConstantesMatematicas.pi / 7;
        if (caso.equalsIgnoreCase("-2*pi/7")) return -2 * ConstantesMatematicas.pi / 7;
        if (caso.equalsIgnoreCase("-e")) return -ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-e*2")) return -ConstantesMatematicas.e * 2;
        if (caso.equalsIgnoreCase("-e*3")) return -ConstantesMatematicas.e * 3;
        if (caso.equalsIgnoreCase("-e*4")) return -ConstantesMatematicas.e * 4;
        if (caso.equalsIgnoreCase("-e*5")) return -ConstantesMatematicas.e * 5;
        if (caso.equalsIgnoreCase("-e*6")) return -ConstantesMatematicas.e * 6;
        if (caso.equalsIgnoreCase("-e*7")) return -ConstantesMatematicas.e * 7;
        if (caso.equalsIgnoreCase("-e*8")) return -ConstantesMatematicas.e * 8;
        if (caso.equalsIgnoreCase("-e*9")) return -ConstantesMatematicas.e * 9;
        if (caso.equalsIgnoreCase("-e*10")) return -ConstantesMatematicas.e * 10;
        if (caso.equalsIgnoreCase("-e*100")) return -ConstantesMatematicas.e * 100;
        if (caso.equalsIgnoreCase("-e/2")) return -ConstantesMatematicas.e / 2;
        if (caso.equalsIgnoreCase("-e/3")) return -ConstantesMatematicas.e / 3;
        if (caso.equalsIgnoreCase("-e/4")) return -ConstantesMatematicas.e / 4;
        if (caso.equalsIgnoreCase("-e/5")) return -ConstantesMatematicas.e / 5;
        if (caso.equalsIgnoreCase("-e/6")) return -ConstantesMatematicas.e / 6;
        if (caso.equalsIgnoreCase("-e/7")) return -ConstantesMatematicas.e / 7;
        if (caso.equalsIgnoreCase("-e/8")) return -ConstantesMatematicas.e / 8;
        if (caso.equalsIgnoreCase("-e/9")) return -ConstantesMatematicas.e / 9;
        if (caso.equalsIgnoreCase("-e/10")) return -ConstantesMatematicas.e / 10;
        if (caso.equalsIgnoreCase("-e/100")) return -ConstantesMatematicas.e / 100;
        if (caso.equalsIgnoreCase("-1/e")) return -1 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-2/e")) return -2 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-3/e")) return -3 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-4/e")) return -4 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-5/e")) return -5 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-6/e")) return -6 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-7/e")) return -7 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-8/e")) return -8 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-9/e")) return -9 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-10/e")) return -10 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-100/e")) return -100 / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-e*3/2")) return -ConstantesMatematicas.e * 3 / 2;
        if (caso.equalsIgnoreCase("-e*2/3")) return -ConstantesMatematicas.e * 2 / 3;
        if (caso.equalsIgnoreCase("-e*3/4")) return -ConstantesMatematicas.e * 3 / 4;
        if (caso.equalsIgnoreCase("-e*5/6")) return -ConstantesMatematicas.e * 5 / 6;
        if (caso.equalsIgnoreCase("-e*4/3")) return -ConstantesMatematicas.e * 4 / 3;
        if (caso.equalsIgnoreCase("-e*6/5")) return -ConstantesMatematicas.e * 6 / 5;
        if (caso.equalsIgnoreCase("-e*7/2")) return -ConstantesMatematicas.e * 7 / 2;
        if (caso.equalsIgnoreCase("-e*9/2")) return -ConstantesMatematicas.e * 9 / 2;
        if (caso.equalsIgnoreCase("-e*2/9")) return -ConstantesMatematicas.e * 2 / 9;
        if (caso.equalsIgnoreCase("-e*7/8")) return -ConstantesMatematicas.e * 7 / 8;
        if (caso.equalsIgnoreCase("-e*8/7")) return -ConstantesMatematicas.e * 8 / 7;
        if (caso.equalsIgnoreCase("-e*2/7")) return -ConstantesMatematicas.e * 2 / 7;
        if (caso.equalsIgnoreCase("-2*e")) return -2 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-3*e")) return -3 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-4*e")) return -4 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-5*e")) return -5 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-6*e")) return -6 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-7*e")) return -7 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-8*e")) return -8 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-9*e")) return -9 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-10*e")) return -10 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-100*e")) return -100 * ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-3*e/2")) return -3 * ConstantesMatematicas.e / 2;
        if (caso.equalsIgnoreCase("-2*e/3")) return -2 * ConstantesMatematicas.e / 3;
        if (caso.equalsIgnoreCase("-3*e/4")) return -3 * ConstantesMatematicas.e / 4;
        if (caso.equalsIgnoreCase("-5*e/6")) return -5 * ConstantesMatematicas.e / 6;
        if (caso.equalsIgnoreCase("-4*e/3")) return -4 * ConstantesMatematicas.e / 3;
        if (caso.equalsIgnoreCase("-6*e/5")) return -6 * ConstantesMatematicas.e / 5;
        if (caso.equalsIgnoreCase("-7*e/2")) return -7 * ConstantesMatematicas.e / 2;
        if (caso.equalsIgnoreCase("-9*e/2")) return -9 * ConstantesMatematicas.e / 2;
        if (caso.equalsIgnoreCase("-2*e/9")) return -2 * ConstantesMatematicas.e / 9;
        if (caso.equalsIgnoreCase("-7*e/8")) return -7 * ConstantesMatematicas.e / 8;
        if (caso.equalsIgnoreCase("-8*e/7")) return -8 * ConstantesMatematicas.e / 7;
        if (caso.equalsIgnoreCase("-2*e/7")) return -2 * ConstantesMatematicas.e / 7;
        if (caso.equalsIgnoreCase("-pi*e")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-e*pi")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("e*pi")) return ConstantesMatematicas.e * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("pi*e")) return ConstantesMatematicas.e * ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("-pi/e")) return -ConstantesMatematicas.pi / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-e/pi")) return -ConstantesMatematicas.e / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("e/pi")) return ConstantesMatematicas.e / ConstantesMatematicas.pi;
        if (caso.equalsIgnoreCase("pi/e")) return ConstantesMatematicas.pi / ConstantesMatematicas.e;
        if (caso.equalsIgnoreCase("-e*pi")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*2*pi")) return -ConstantesMatematicas.e * 2 * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*3*pi")) return -ConstantesMatematicas.e * 3 * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*4*pi")) return -ConstantesMatematicas.e * 4 * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*5*pi")) return -ConstantesMatematicas.e * 5 * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*6*pi")) return -ConstantesMatematicas.e * 6 * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*7*pi")) return -ConstantesMatematicas.e * 7 * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*8*pi")) return -ConstantesMatematicas.e * 8 * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*9*pi")) return -ConstantesMatematicas.e * 9 * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*10*pi")) return -ConstantesMatematicas.e * 10 * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*100*pi")) return -ConstantesMatematicas.e * 100 * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*pi/2")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi / 2;
    if (caso.equalsIgnoreCase("-e*pi/3")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi / 3;
    if (caso.equalsIgnoreCase("-e*pi/4")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi / 4;
    if (caso.equalsIgnoreCase("-e*pi/5")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi / 5;
    if (caso.equalsIgnoreCase("-e*pi/6")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi / 6;
    if (caso.equalsIgnoreCase("-e*pi/7")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi / 7;
    if (caso.equalsIgnoreCase("-e*pi/8")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi / 8;
    if (caso.equalsIgnoreCase("-e*pi/9")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi / 9;
    if (caso.equalsIgnoreCase("-e*pi/10")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi / 10;
    if (caso.equalsIgnoreCase("-e*pi/100")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi / 100;
    if (caso.equalsIgnoreCase("-1/e*pi")) return -1 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-2/e*pi")) return -2 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-3/e*pi")) return -3 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-4/e*pi")) return -4 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-5/e*pi")) return -5 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-6/e*pi")) return -6 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-7/e*pi")) return -7 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-8/e*pi")) return -8 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-9/e*pi")) return -9 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-10/e*pi")) return -10 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-100/e*pi")) return -100 / ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-e*pi*3/2")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 3 / 2;
    if (caso.equalsIgnoreCase("-e*pi*2/3")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 2 / 3;
    if (caso.equalsIgnoreCase("-e*pi*3/4")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 3 / 4;
    if (caso.equalsIgnoreCase("-e*pi*5/6")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 5 / 6;
    if (caso.equalsIgnoreCase("-e*pi*4/3")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 4 / 3;
    if (caso.equalsIgnoreCase("-e*pi*6/5")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 6 / 5;
    if (caso.equalsIgnoreCase("-e*pi*7/2")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 7 / 2;
    if (caso.equalsIgnoreCase("-e*pi*9/2")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 9 / 2;
    if (caso.equalsIgnoreCase("-e*pi*2/9")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 2 / 9;
    if (caso.equalsIgnoreCase("-e*pi*7/8")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 7 / 8;
    if (caso.equalsIgnoreCase("-e*pi*8/7")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 8 / 7;
    if (caso.equalsIgnoreCase("-e*pi*2/7")) return -ConstantesMatematicas.e * ConstantesMatematicas.pi * 2 / 7;
    if (caso.equalsIgnoreCase("-2*e*pi")) return -2 * ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-3*e*pi")) return -3 * ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-4*e*pi")) return -4 * ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-5*e*pi")) return -5 * ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-6*e*pi")) return -6 * ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-7*e*pi")) return -7 * ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-8*e*pi")) return -8 * ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-9*e*pi")) return -9 * ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-10*e*pi")) return -10 * ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-100*e*pi")) return -100 * ConstantesMatematicas.e * ConstantesMatematicas.pi;
    if (caso.equalsIgnoreCase("-3*e*pi/2")) return -3 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 2;
    if (caso.equalsIgnoreCase("-2*e*pi/3")) return -2 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 3;
    if (caso.equalsIgnoreCase("-3*e*pi/4")) return -3 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 4;
    if (caso.equalsIgnoreCase("-5*e*pi/6")) return -5 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 6;
    if (caso.equalsIgnoreCase("-4*e*pi/3")) return -4 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 3;
    if (caso.equalsIgnoreCase("-6*e*pi/5")) return -6 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 5;
    if (caso.equalsIgnoreCase("-7*e*pi/2")) return -7 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 2;
    if (caso.equalsIgnoreCase("-9*e*pi/2")) return -9 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 2;
    if (caso.equalsIgnoreCase("-2*e*pi/9")) return -2 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 9;
    if (caso.equalsIgnoreCase("-7*e*pi/8")) return -7 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 8;
    if (caso.equalsIgnoreCase("-8*e*pi/7")) return -8 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 7;
    if (caso.equalsIgnoreCase("-2*e*pi/7")) return -2 * ConstantesMatematicas.e * ConstantesMatematicas.pi / 7;
    if (caso.equalsIgnoreCase("i*i")) return (-1);
    if (caso.equalsIgnoreCase("-i*i")) return (1);
    if (caso.equalsIgnoreCase("i^2")) return (-1);
    if (caso.equalsIgnoreCase("-i^2")) return (1);
    if (caso.equalsIgnoreCase("i^4")) return (1);
    if (caso.equalsIgnoreCase("-i^4")) return (-1);
    if (caso.equalsIgnoreCase("i^6")) return (1);
    if (caso.equalsIgnoreCase("-i^6")) return (-1);
    if (caso.equalsIgnoreCase("i^8")) return (1);
    if (caso.equalsIgnoreCase("-i^8")) return (-1);
    if (caso.equalsIgnoreCase("i^i")) return (ConstantesMatematicas.iElevadoi);
    if (caso.equalsIgnoreCase("-i^i")) return (-ConstantesMatematicas.iElevadoi);
    if (caso.equalsIgnoreCase("i^-i")) return (ConstantesMatematicas.iElevadoAMenosi);
    if (caso.equalsIgnoreCase("-i^i")) return (-ConstantesMatematicas.iElevadoAMenosi);
    
    
    

        
        
        throw new IllegalArgumentException("Caso no encontrado: " + caso);
    }
    
}
